/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ImageGallery: typeof import('./src/components/ImageGallery.vue')['default']
    InstructionsPopup: typeof import('./src/components/InstructionsPopup.vue')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
  }
}
